### ISSUE TITLE
direnv: error: attribute 'lorri-eval-patched' missing, at (string):1:2

### ISSUE THREAD

**Issue by vroad** [shajra/direnv-nix-lorelei#7]
Stopped working after updating direnv-nix-lorelei to ba5f6645143caa0a5cb5eb9d424fe0eb0c426068 on my mac. Last version that worked on my machine is f81a6e7e77be2e2265c5a68ad798a9f6ed6e3dae

I deleted my own home-manager module in my home-manager config repo and switched to the one created by you, but I guess this change is not relevant to the issue.

https://github.com/shajra/direnv-nix-lorelei/issues/4

```
direnv: loading ~/my-app/.envrc
direnv: initializing cache
direnv: rebuilding with Nix
direnv: error: attribute 'lorri-eval-patched' missing, at (string):1:2
direnv: ERROR: Nix build failed
```

I looked into generated shell scripts to see what's happening, and found the lines possibly caused build failure.
`lorri-eval-patched` no longer exists in current version of the package. (confirmed with auto completion of `nix repl`)

https://github.com/shajra/direnv-nix-lorelei/blob/ba5f6645143caa0a5cb5eb9d424fe0eb0c426068/nix/direnv-nix-lorelei.nix#L82
https://github.com/shajra/direnv-nix-lorelei/blob/ba5f6645143caa0a5cb5eb9d424fe0eb0c426068/nix/direnv-nix-lorelei.nix#L421

```
--expr "((import /nix/store/ra2fzvpx1il2qyx5lcxgwx5xw0l6lnn2-source {}).lorri-eval-$auto_watch_eval)"
```

```
nix-repl> lorelei = ((import /nix/store/ra2fzvpx1il2qyx5lcxgwx5xw0l6lnn2-source {}))

nix-repl> lorelei.
lorelei.distribution  lorelei.nix-project   lorelei.nixpkgs
```

Previous version did have `lorri-eval-patched`.

https://github.com/shajra/direnv-nix-lorelei/blob/f81a6e7e77be2e2265c5a68ad798a9f6ed6e3dae/nix/default.nix#L58

**Comment by shajra** [comment]
Shoot.  I was making changes to the build that shouldn't have affected the script.  I got a false confidence, and didn't test everything correctly, evidently.

I think this is an easy fix, I'll try to do it today.

**Comment by shajra** [comment]
As expected, this is on Linux as well as Mac.  My testing missed this, sorry.  As least it's reproduced.  Working on it now.

**Comment by shajra** [comment]
@vroad the GitHub comment auto-closed this.  I tested it out on my end, so I didn't feel as badly pushing it out to the main branch.  But please comment back that the fix is working on your end as well.

**Comment by shajra** [comment]
@vroad Hey, I'll also be interested if the Home Manager module is working for you, because that's new code.

**Comment by shajra** [comment]
Man... there were multiple things errant with my manual testing.  I always believe in testing, but for personal projects, I sometimes leave manual testing as an option, because the work to automate testing completely isn't always worth it.  I have these supporting scripts, but they require too many assumptions that are easily broken.

I think I'm overthinking the complexity of testing this.  I have a feeling it's pretty easy to test in a Nix expression.  That will be a controlled environment.

**Comment by vroad** [comment]
Thank you, home manager module from this repo is now working.

For testing, Something that ensures core functionality of lorelei is not broken at least might still be useful. Testing all combination of arguments is often difficult to achieve.
